---
##create user
user_name: test1
user_password: Test1!
#user_groups: test1

##change hostname
host_name: test-web01

##Apache
serveradmin: test@example.com
domain_name: test.com

##MySQL
root_password: Testtest991!
db_user_name: test_user
db_user_password: Kenshirou913!
db_name: test_db

##dokcer-compose URL
dokcer-compose_url: https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)