---
##create user
user_name: test1
user_password: Test1!
#user_groups: test1

##change hostname
host_name: test-web01

##Apache
serveradmin: test@example.com
domain_name: test.com

##MySQL
root_password: Testtest991!

##dokcer-compose URL
docker_compose_url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64

##zabbix repository URL
zabbix_repository_url: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm

##zabbix server IP
zabbix_server_ip: 192.168.33.80

##zabbix mysql pass
zabbix_dbpass: Zabbixmysql991!