---
- name: install MySQL-python
  yum:
    name: MySQL-python
    state: present

- name: create zabbix-user
  mysql_user:
    login_user: root
    login_password: "{{ root_password }}"
    name: zabbix
    host: localhost
    password: "{{ zabbix_dbpass }}"
    priv: "*.*:process"
    state: present
  ignore_errors: yes

- name: create dir
  file:
    path: /var/lib/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0755

- name: put my.cnf
  template:
    src: ../templates/my.cnf
    dest: /var/lib/zabbix/.my.cnf
    owner: zabbix
    group: zabbix
    mode: 0644
