---
- name: install repository for docker
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install packages
  yum: 
    name: "{{item}}" 
    state: present
  with_items:
    - yum-utils

- name: install docker
  yum: 
    name: "{{item}}" 
    state: present
    enablerepo: docker-ce
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: start and enable docker
  service:
    name: dokcer
    state: started
    enabled: yes

- name: get url for docker-compose
  get_url:
    url: "{{ dokcer-compose_url }}"
    dest: /usr/local/bin/docker-compose

- name: add an execution permission
  file:
    path: /usr/local/bin/docker-compose
    mode: '+x'

- name: create a symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
    force: yes
