---
- name: install packages
  yum: 
    name: "{{item}}" 
    state: present
  with_items:
    - yum-utils

- name: install docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: enable docker repository
  command: yum-config-manager --enable docker-ce-edge

- name: install docker
  yum: 
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - python3-pip

- name: start and enable docker
  service:
    name: docker
    state: started
    enabled: yes

- name: get url for docker-compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose

- name: add an execution permission
  file:
    path: /usr/local/bin/docker-compose
    mode: '+x'

- name: create a symlink
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
    force: yes