---
- name: install epel and remi repository
  yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    disable_gpg_check: yes

- name: install php
  yum: 
    name: "{{item}}" 
    state: present
    enablerepo: "remi-php{{ php_version}}"
  with_items:
    - "{{ php_modules }}"


- name: copy php.ini
  copy:
    src: ../templates/php.ini
    dest: /etc